CFG_PACKAGE = ENV['SPRINGBOOT_DEMO_CUSTOMER_PACKAGE_NAME']
CFG_TZ = "Australia/Sydney"     

provisioning_script = <<SCRIPT
#!/bin/bash
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata
#grep craigiebabe /etc/apt/sources.list || echo "deb http://craigiebabe.net:9081/nexus/content/repositories/releases/ ./" >> /etc/apt/sources.list
grep craigiebabe /etc/apt/sources.list || echo "deb http://craigiebabe.net:9081/nexus/content/repositories/snapshots/ ./" >> /etc/apt/sources.list
apt-get update
apt-get install vim curl zip unzip -y --no-upgrade
apt-get install openjdk-7-jre -y --no-upgrade
echo "apt-get install #{CFG_PACKAGE}"
echo Provisioning is complete
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "gce"

  config.vm.provision :shell, :inline => provisioning_script
  #config.vm.provision :shell, :path => 'startup.sh'

  #config.vm.network :forwarded_port, guest: 80, host: 8080 # ignored by google provider

  config.vm.provider :google do |google, override|

    google.image = "debian-7-wheezy-v20150127"
    google.machine_type = "n1-standard-1"
    google.zone = "us-central1-f"

    google.google_project_id = "white-academy-519"
    google.google_client_email = "444910770229-m59qh9g00ll5j45elnongpgqtvp953j7@developer.gserviceaccount.com"
    google.google_json_key_location = ENV['HOME'] + "/.ssh/gce_vagrant.json"

    google.name = "prod-microservices-demo"

    google.tags = ['http-server', 'https-server'] # these tags will trigger opening of ports 80 and 443

    if ENV['GOOGLE_SSH_USER'] and ENV['GOOGLE_SSH_KEY_LOCATION']
        override.ssh.username = ENV['GOOGLE_SSH_USER']
        override.ssh.private_key_path = ENV['GOOGLE_SSH_KEY_LOCATION']
    else
        override.ssh.username = ENV['USER']
        override.ssh.private_key_path = ENV['HOME'] + "/.ssh/id_rsa"
    end
  end

end
