#Adjustable settings
CFG_TZ = "Australia/Sydney"     

provisioning_script = <<SCRIPT
#!/bin/bash
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata
apt-get update
apt-get install vim curl zip unzip -y --no-upgrade
apt-get install openjdk-7-jre -y --no-upgrade
echo Provisioning is complete
SCRIPT

Vagrant.configure("2") do |config|

  #config.user.defaults = {
  #  "ssh" => {
  #    "private_key_path" => "~/.ssh/id_rsa",
  #    "username" => "craig"
  #  }
  #}

  config.vm.box = "gce"

  config.vm.provision :shell, :inline => provisioning_script
  #config.vm.provision :shell, :path => 'startup.sh'

  #config.vm.network :forwarded_port, guest: 80, host: 8080 # ignored by google provider

  config.vm.provider :google do |google, override|

    google.image = "debian-7-wheezy-v20150127"
    google.machine_type = "n1-standard-1"
    google.zone = "us-central1-f"

    google.google_project_id = "white-academy-519"
    google.google_client_email = "444910770229-m59qh9g00ll5j45elnongpgqtvp953j7@developer.gserviceaccount.com"
    google.name = "microservices-demo-integration-testing"
    google.google_json_key_location = "./gce_vagrant.json"

    google.tags = ['http-server', 'https-server']

    override.ssh.username = "craig"
    override.ssh.private_key_path = "/home/craig/.ssh/id_rsa"
    # override.ssh.private_key_path = config.user.ssh.private_key_path
    # override.ssh.username = config.user.ssh.username
    # override.ssh.username = ENV['USER']
    # override.ssh.private_key_path = ENV['USER_KEYPATH']
    # if ENV['GOOGLE_SSH_USER'] and ENV['GOOGLE_SSH_KEY_LOCATION']
    #     override.ssh.username = ENV['GOOGLE_SSH_USER']
    #     override.ssh.private_key_path = ENV['GOOGLE_SSH_KEY_LOCATION']
    # end
  end

end

